services:
  devpot:
    build:
      context: build-config/.
      args:
        TZ: ${TZ}
        NODE_VERSION: ${NODE_VERSION}
        GIT_USER_NAME: ${GIT_USER_NAME}
        GIT_USER_EMAIL: ${GIT_USER_EMAIL}
        GIT_USERNAME: ${GIT_USERNAME}
    container_name: devpot
    hostname: devpot
    env_file: .env
    privileged: true
    ports:
      - "1022:22"
    networks:
      - devpot_network
    volumes:
      - ./data/ssh/ssh-keys.pub:/tmp/ssh-keys.pub
      - ./data/onedrive/config:/root/.config/onedrive/config
      - devpot_workspace:/workspace
      # Making docker-in-docker work
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
volumes:
  devpot_workspace:
    driver: local
networks:
  devpot_network:
    name: devpot_network
