version: "3.6"

services:
  devpot:
    build:
      context: build-config/.
      args:
        TZ: ${TZ}
        NODE_VERSION: ${NODE_VERSION}
        GIT_USER_NAME: ${GIT_USER_NAME}
        GIT_USER_EMAIL: ${GIT_USER_EMAIL}
    container_name: devpot
    env_file: .env
    privileged: true
    ports:
      - "1022:22"
    volumes:
      - ./data/ssh/ssh-keys.pub:/tmp/ssh-keys.pub
      - ./data/onedrive/config:/root/.config/onedrive/config
      - ./workspace:/workspace
    restart: always
